package darculaforest

fun Palette.generateAlacritty() = """
    # Darcula Forest — generated by ./gradlew run
    [colors]
    indexed_colors = [{ index = 16, color = "#${hexOf(editorBg)}" }]

    [colors.primary]
    background = "#${hexOf(editorBg)}"
    foreground = "#${hexOf(fg)}"

    [colors.normal]
    black   = "#${hexOf(termBlack)}"
    red     = "#${hexOf(termRed)}"
    green   = "#${hexOf(termGreen)}"
    yellow  = "#${hexOf(termYellow)}"
    blue    = "#${hexOf(termBlue)}"
    magenta = "#${hexOf(termMagenta)}"
    cyan    = "#${hexOf(termCyan)}"
    white   = "#${hexOf(termWhite)}"

    [colors.bright]
    black   = "#${hexOf(termBrightBlack)}"
    red     = "#${hexOf(termBrightRed)}"
    green   = "#${hexOf(termBrightGreen)}"
    yellow  = "#${hexOf(termBrightYellow)}"
    blue    = "#${hexOf(termBrightBlue)}"
    magenta = "#${hexOf(termBrightMagenta)}"
    cyan    = "#${hexOf(termBrightCyan)}"
    white   = "#${hexOf(termBrightWhite)}"
""".trimIndent()
