package darculaforest

import darculaforest.Expr.Var
import kotlinx.serialization.ExperimentalSerializationApi
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.Json

// ── VS Code color theme ─────────────────────────────────────────────
// Emitted as a minimal extension: vscode/package.json + vscode/themes/<theme>.json.
// Workbench colors follow Zed's UI choices (chrome = gutterBg, panels = panelBg);
// TextMate scopes and semantic tokens follow the IntelliJ/Zed syntax mapping.

@Serializable
data class VsCodeTheme(
    @SerialName("\$schema") val schema: String,
    val name: String,
    val type: String,
    val semanticHighlighting: Boolean,
    val colors: Map<String, String>,
    val tokenColors: List<VsCodeTokenColor>,
    val semanticTokenColors: Map<String, VsCodeTokenSettings>,
)

@Serializable
data class VsCodeTokenColor(val name: String, val scope: List<String>, val settings: VsCodeTokenSettings)

@Serializable
data class VsCodeTokenSettings(val foreground: String? = null, val fontStyle: String? = null)

private fun token(name: String, vararg scope: String, fg: Var? = null, style: String? = null) =
    VsCodeTokenColor(name, scope.toList(), VsCodeTokenSettings(fg?.let(::hex), style))

private fun style(fg: Var? = null, style: String? = null) = VsCodeTokenSettings(fg?.let(::hex), style)

private val Palette.workbenchColors: Map<String, Var> get() = linkedMapOf(
    // Base
    "focusBorder"                to keyword,
    "foreground"                 to fg,
    "disabledForeground"         to textPlaceholder,
    "descriptionForeground"      to textMuted,
    "errorForeground"            to error,
    "icon.foreground"            to fg,
    "selection.background"       to selectionBg,
    "widget.border"              to borderColor,
    "widget.shadow"              to pageBg,
    "sash.hoverBorder"           to keyword,

    // Text
    "textLink.foreground"        to keyword,
    "textLink.activeForeground"  to functionDecl,
    "textPreformat.foreground"   to string,
    "textPreformat.background"   to injectedLangBg,
    "textBlockQuote.background"  to caretRow,
    "textBlockQuote.border"      to borderColor,
    "textCodeBlock.background"   to injectedLangBg,
    "textSeparator.foreground"   to borderColor,

    // Buttons, inputs, dropdowns
    "button.background"                to keyword,
    "button.foreground"                to editorBg,
    "button.hoverBackground"           to functionDecl,
    "button.secondaryBackground"       to elementHover,
    "button.secondaryForeground"       to fg,
    "button.secondaryHoverBackground"  to elementActive,
    "checkbox.background"              to elementHover,
    "checkbox.border"                  to borderColor,
    "checkbox.foreground"              to fg,
    "dropdown.background"              to panelBg,
    "dropdown.listBackground"          to panelBg,
    "dropdown.border"                  to borderColor,
    "dropdown.foreground"              to fg,
    "input.background"                 to panelBg,
    "input.border"                     to borderColor,
    "input.foreground"                 to fg,
    "input.placeholderForeground"      to textPlaceholder,
    "inputOption.activeBackground"     to selectionBg,
    "inputOption.activeBorder"         to keyword,
    "inputOption.activeForeground"     to fg,
    "inputValidation.errorBackground"  to errorBg,
    "inputValidation.errorBorder"      to errorBorder,
    "inputValidation.infoBackground"   to infoBg,
    "inputValidation.infoBorder"       to infoBorder,
    "inputValidation.warningBackground" to warningBg,
    "inputValidation.warningBorder"    to warningBorder,

    // Scrollbar, badge, progress
    "scrollbar.shadow"                 to pageBg,
    "scrollbarSlider.background"       to scrollbarThumb,
    "scrollbarSlider.hoverBackground"  to elementActive,
    "scrollbarSlider.activeBackground" to lineNumber,
    "badge.background"                 to keyword,
    "badge.foreground"                 to editorBg,
    "progressBar.background"           to keyword,

    // Lists and trees
    "list.activeSelectionBackground"   to selectionBg,
    "list.activeSelectionForeground"   to fg,
    "list.inactiveSelectionBackground" to elementHover,
    "list.hoverBackground"             to elementHover,
    "list.focusBackground"             to selectionBg,
    "list.focusOutline"                to keyword,
    "list.inactiveFocusOutline"        to borderColor,
    "list.highlightForeground"         to functionDecl,
    "list.dropBackground"              to selectionBg,
    "list.errorForeground"             to error,
    "list.warningForeground"           to todo,
    "listFilterWidget.background"      to panelBg,
    "listFilterWidget.outline"         to keyword,
    "listFilterWidget.noMatchesOutline" to error,
    "tree.indentGuidesStroke"          to borderVariant,

    // Activity bar
    "activityBar.background"           to gutterBg,
    "activityBar.foreground"           to fg,
    "activityBar.inactiveForeground"   to textMuted,
    "activityBar.border"               to borderColor,
    "activityBar.activeBorder"         to keyword,
    "activityBarBadge.background"      to keyword,
    "activityBarBadge.foreground"      to editorBg,

    // Side bar
    "sideBar.background"               to panelBg,
    "sideBar.foreground"               to fg,
    "sideBar.border"                   to borderColor,
    "sideBarTitle.foreground"          to fg,
    "sideBarSectionHeader.background"  to panelBg,
    "sideBarSectionHeader.foreground"  to fg,
    "sideBarSectionHeader.border"      to borderVariant,

    // Minimap
    "minimap.background"               to editorBg,
    "minimap.selectionHighlight"       to selectionBg,
    "minimap.findMatchHighlight"       to searchResultStripe,
    "minimap.errorHighlight"           to error,
    "minimap.warningHighlight"         to todo,
    "minimapGutter.addedBackground"    to diffAddStripe,
    "minimapGutter.modifiedBackground" to diffChangeStripe,
    "minimapGutter.deletedBackground"  to diffDeleteStripe,

    // Editor groups and tabs
    "editorGroup.border"                 to borderColor,
    "editorGroup.dropBackground"         to selectionBg,
    "editorGroupHeader.tabsBackground"   to panelBg,
    "editorGroupHeader.tabsBorder"       to borderVariant,
    "editorGroupHeader.noTabsBackground" to editorBg,
    "tab.activeBackground"               to editorBg,
    "tab.activeForeground"               to fg,
    "tab.activeBorder"                   to keyword,
    "tab.activeBorderTop"                to transparent,
    "tab.border"                         to borderVariant,
    "tab.inactiveBackground"             to panelBg,
    "tab.inactiveForeground"             to textMuted,
    "tab.hoverBackground"                to elementHover,
    "tab.unfocusedActiveForeground"      to textMuted,
    "tab.unfocusedInactiveForeground"    to textPlaceholder,
    "tab.lastPinnedBorder"               to borderColor,

    // Editor
    "editor.background"                       to editorBg,
    "editor.foreground"                       to fg,
    "editorLineNumber.foreground"             to lineNumber,
    "editorLineNumber.activeForeground"       to fg,
    "editorCursor.foreground"                 to fg,
    "editorCursor.background"                 to editorBg,
    "editor.selectionBackground"              to selectionBg,
    "editor.inactiveSelectionBackground"      to elementHover,
    "editor.selectionHighlightBackground"     to searchResultBg,
    "editor.wordHighlightBackground"          to elementActive,
    "editor.wordHighlightStrongBackground"    to matchingBraceBg,
    "editor.findMatchBackground"              to searchResultStripe,
    "editor.findMatchHighlightBackground"     to searchResultBg,
    "editor.findRangeHighlightBackground"     to caretRow,
    "editor.hoverHighlightBackground"         to elementHover,
    "editor.lineHighlightBackground"          to caretRow,
    "editor.lineHighlightBorder"              to caretRow,
    "editor.rangeHighlightBackground"         to caretRow,
    "editor.foldBackground"                   to foldedTextBg,
    "editorLink.activeForeground"             to keyword,
    "editorWhitespace.foreground"             to borderColor,
    "editorIndentGuide.background1"           to borderVariant,
    "editorIndentGuide.activeBackground1"     to borderColor,
    "editorRuler.foreground"                  to borderVariant,
    "editorCodeLens.foreground"               to textMuted,
    "editorBracketMatch.background"           to matchingBraceBg,
    "editorBracketMatch.border"               to transparent,
    "editorBracketHighlight.foreground1"      to parens,
    "editorBracketHighlight.foreground2"      to parens,
    "editorBracketHighlight.foreground3"      to parens,
    "editorBracketHighlight.foreground4"      to parens,
    "editorBracketHighlight.foreground5"      to parens,
    "editorBracketHighlight.foreground6"      to parens,
    "editorBracketHighlight.unexpectedBracket.foreground" to error,
    "editorError.foreground"                  to error,
    "editorWarning.foreground"                to todo,
    "editorInfo.foreground"                   to diffChangeStripe,
    "editorHint.foreground"                   to textMuted,
    "editorUnnecessaryCode.opacity"           to unusedElementOpacity,
    "editorGutter.background"                 to gutterBg,
    "editorGutter.modifiedBackground"         to diffChangeStripe,
    "editorGutter.addedBackground"            to diffAddStripe,
    "editorGutter.deletedBackground"          to diffDeleteStripe,
    "editorGutter.foldingControlForeground"   to textMuted,
    "editorGutter.commentRangeForeground"     to lineNumber,
    "editorInlayHint.background"              to caretRow,
    "editorInlayHint.foreground"              to textMuted,
    "editorStickyScroll.background"           to editorBg,
    "editorStickyScroll.border"               to borderVariant,
    "editorStickyScroll.shadow"               to pageBg,
    "editorOverviewRuler.border"              to borderVariant,
    "editorOverviewRuler.findMatchForeground" to searchResultStripe,
    "editorOverviewRuler.modifiedForeground"  to diffChangeStripe,
    "editorOverviewRuler.addedForeground"     to diffAddStripe,
    "editorOverviewRuler.deletedForeground"   to diffDeleteStripe,
    "editorOverviewRuler.errorForeground"     to error,
    "editorOverviewRuler.warningForeground"   to warningStripe,
    "editorOverviewRuler.infoForeground"      to diffChangeStripe,
    "editorOverviewRuler.bracketMatchForeground" to matchingBraceFg,

    // Editor widgets
    "editorWidget.background"                   to panelBg,
    "editorWidget.foreground"                   to fg,
    "editorWidget.border"                       to borderColor,
    "editorWidget.resizeBorder"                 to keyword,
    "editorSuggestWidget.background"            to panelBg,
    "editorSuggestWidget.border"                to borderColor,
    "editorSuggestWidget.foreground"            to fg,
    "editorSuggestWidget.highlightForeground"   to functionDecl,
    "editorSuggestWidget.focusHighlightForeground" to functionDecl,
    "editorSuggestWidget.selectedBackground"    to selectionBg,
    "editorSuggestWidget.selectedForeground"    to fg,
    "editorHoverWidget.background"              to docBg,
    "editorHoverWidget.foreground"              to fg,
    "editorHoverWidget.border"                  to borderColor,
    "editorMarkerNavigation.background"         to panelBg,
    "editorMarkerNavigationError.background"    to error,
    "editorMarkerNavigationWarning.background"  to todo,
    "editorMarkerNavigationInfo.background"     to diffChangeStripe,
    "debugExceptionWidget.background"           to errorBg,
    "debugExceptionWidget.border"               to errorBorder,

    // Diff editor
    "diffEditor.insertedTextBackground"         to diffAdd,
    "diffEditor.insertedLineBackground"         to successBg,
    "diffEditor.removedTextBackground"          to diffDelete,
    "diffEditor.removedLineBackground"          to elementHover,
    "diffEditor.diagonalFill"                   to borderVariant,
    "diffEditor.border"                         to borderColor,
    "diffEditorGutter.insertedLineBackground"   to successBg,
    "diffEditorGutter.removedLineBackground"    to elementHover,
    "diffEditorOverview.insertedForeground"     to diffAddStripe,
    "diffEditorOverview.removedForeground"      to diffDeleteStripe,

    // Peek view
    "peekView.border"                           to keyword,
    "peekViewEditor.background"                 to caretRow,
    "peekViewEditor.matchHighlightBackground"   to searchResultBg,
    "peekViewResult.background"                 to panelBg,
    "peekViewResult.fileForeground"             to fg,
    "peekViewResult.lineForeground"             to textMuted,
    "peekViewResult.matchHighlightBackground"   to searchResultBg,
    "peekViewResult.selectionBackground"        to selectionBg,
    "peekViewResult.selectionForeground"        to fg,
    "peekViewTitle.background"                  to panelBg,
    "peekViewTitleLabel.foreground"             to fg,
    "peekViewTitleDescription.foreground"       to textMuted,

    // Merge conflicts
    "merge.currentHeaderBackground"    to successBorder,
    "merge.currentContentBackground"   to successBg,
    "merge.incomingHeaderBackground"   to infoBorder,
    "merge.incomingContentBackground"  to infoBg,
    "merge.commonHeaderBackground"     to elementActive,
    "merge.commonContentBackground"    to elementHover,
    "merge.border"                     to borderColor,

    // Panel
    "panel.background"                 to editorBg,
    "panel.border"                     to borderColor,
    "panelTitle.activeBorder"          to keyword,
    "panelTitle.activeForeground"      to fg,
    "panelTitle.inactiveForeground"    to textMuted,
    "panelInput.border"                to borderColor,
    "panelSection.border"              to borderVariant,

    // Status bar
    "statusBar.background"                   to gutterBg,
    "statusBar.foreground"                   to fg,
    "statusBar.border"                       to borderColor,
    "statusBar.focusBorder"                  to keyword,
    "statusBar.noFolderBackground"           to gutterBg,
    "statusBar.debuggingBackground"          to warningBorder,
    "statusBar.debuggingForeground"          to fg,
    "statusBarItem.activeBackground"         to elementActive,
    "statusBarItem.hoverBackground"          to elementHover,
    "statusBarItem.focusBorder"              to keyword,
    "statusBarItem.prominentBackground"      to keyword,
    "statusBarItem.prominentForeground"      to editorBg,
    "statusBarItem.prominentHoverBackground" to functionDecl,
    "statusBarItem.remoteBackground"         to keyword,
    "statusBarItem.remoteForeground"         to editorBg,
    "statusBarItem.errorBackground"          to error,
    "statusBarItem.errorForeground"          to editorBg,
    "statusBarItem.warningBackground"        to todo,
    "statusBarItem.warningForeground"        to editorBg,

    // Title bar, menus, command center
    "titleBar.activeBackground"        to gutterBg,
    "titleBar.activeForeground"        to fg,
    "titleBar.inactiveBackground"      to caretRow,
    "titleBar.inactiveForeground"      to textMuted,
    "titleBar.border"                  to borderColor,
    "menubar.selectionBackground"      to elementHover,
    "menubar.selectionForeground"      to fg,
    "menu.background"                  to panelBg,
    "menu.foreground"                  to fg,
    "menu.selectionBackground"         to selectionBg,
    "menu.selectionForeground"         to fg,
    "menu.separatorBackground"         to borderColor,
    "menu.border"                      to borderColor,
    "commandCenter.background"         to caretRow,
    "commandCenter.foreground"         to textMuted,
    "commandCenter.border"             to borderColor,
    "commandCenter.activeBackground"   to elementHover,
    "commandCenter.activeForeground"   to fg,

    // Notifications, banner
    "notificationCenter.border"              to borderColor,
    "notificationCenterHeader.background"    to panelBg,
    "notificationCenterHeader.foreground"    to fg,
    "notificationToast.border"               to borderColor,
    "notifications.background"               to panelBg,
    "notifications.foreground"               to fg,
    "notifications.border"                   to borderColor,
    "notificationLink.foreground"            to keyword,
    "notificationsErrorIcon.foreground"      to error,
    "notificationsWarningIcon.foreground"    to todo,
    "notificationsInfoIcon.foreground"       to diffChangeStripe,
    "banner.background"                      to elementActive,
    "banner.foreground"                      to fg,
    "banner.iconForeground"                  to keyword,

    // Extensions, quick picker, keybindings
    "extensionButton.prominentBackground"       to keyword,
    "extensionButton.prominentForeground"       to editorBg,
    "extensionButton.prominentHoverBackground"  to functionDecl,
    "extensionBadge.remoteBackground"           to keyword,
    "extensionBadge.remoteForeground"           to editorBg,
    "extensionIcon.starForeground"              to todo,
    "extensionIcon.verifiedForeground"          to keyword,
    "extensionIcon.preReleaseForeground"        to constantField,
    "pickerGroup.border"                        to borderColor,
    "pickerGroup.foreground"                    to keyword,
    "quickInput.background"                     to panelBg,
    "quickInput.foreground"                     to fg,
    "quickInputList.focusBackground"            to selectionBg,
    "quickInputList.focusForeground"            to fg,
    "quickInputTitle.background"                to panelBg,
    "keybindingLabel.background"                to elementHover,
    "keybindingLabel.foreground"                to fg,
    "keybindingLabel.border"                    to borderColor,
    "keybindingLabel.bottomBorder"              to borderColor,

    // Integrated terminal
    "terminal.background"                to editorBg,
    "terminal.foreground"                to fg,
    "terminal.border"                    to borderColor,
    "terminal.selectionBackground"       to selectionBg,
    "terminal.findMatchBackground"       to searchResultStripe,
    "terminal.findMatchHighlightBackground" to searchResultBg,
    "terminal.tab.activeBorder"          to keyword,
    "terminalCursor.foreground"          to fg,
    "terminalCursor.background"          to editorBg,
    "terminalCommandDecoration.defaultBackground" to textMuted,
    "terminalCommandDecoration.successBackground" to diffAddStripe,
    "terminalCommandDecoration.errorBackground"   to error,
    "terminalStickyScroll.background"    to caretRow,
    "terminalStickyScrollHover.background" to elementHover,
    "terminal.ansiBlack"                 to termBlack,
    "terminal.ansiRed"                   to termRed,
    "terminal.ansiGreen"                 to termGreen,
    "terminal.ansiYellow"                to termYellow,
    "terminal.ansiBlue"                  to termBlue,
    "terminal.ansiMagenta"               to termMagenta,
    "terminal.ansiCyan"                  to termCyan,
    "terminal.ansiWhite"                 to termWhite,
    "terminal.ansiBrightBlack"           to termBrightBlack,
    "terminal.ansiBrightRed"             to termBrightRed,
    "terminal.ansiBrightGreen"           to termBrightGreen,
    "terminal.ansiBrightYellow"          to termBrightYellow,
    "terminal.ansiBrightBlue"            to termBrightBlue,
    "terminal.ansiBrightMagenta"         to termBrightMagenta,
    "terminal.ansiBrightCyan"            to termBrightCyan,
    "terminal.ansiBrightWhite"           to termBrightWhite,

    // Debug
    "debugToolBar.background"                   to panelBg,
    "debugToolBar.border"                       to borderColor,
    "debugIcon.breakpointForeground"            to error,
    "debugIcon.breakpointDisabledForeground"    to textPlaceholder,
    "debugIcon.startForeground"                 to diffAddStripe,
    "debugIcon.pauseForeground"                 to todo,
    "debugIcon.stopForeground"                  to error,
    "debugIcon.disconnectForeground"            to error,
    "debugIcon.restartForeground"               to diffAddStripe,
    "debugIcon.continueForeground"              to diffAddStripe,
    "debugIcon.stepOverForeground"              to keyword,
    "debugIcon.stepIntoForeground"              to keyword,
    "debugIcon.stepOutForeground"               to keyword,
    "debugIcon.stepBackForeground"              to keyword,
    "debugConsole.infoForeground"               to diffChangeStripe,
    "debugConsole.warningForeground"            to todo,
    "debugConsole.errorForeground"              to error,
    "debugConsole.sourceForeground"             to fg,
    "debugConsoleInputIcon.foreground"          to keyword,
    "debugTokenExpression.name"                 to functionDecl,
    "debugTokenExpression.value"                to fg,
    "debugTokenExpression.string"               to string,
    "debugTokenExpression.boolean"              to keyword,
    "debugTokenExpression.number"               to number,
    "debugTokenExpression.error"                to error,
    "debugView.exceptionLabelBackground"        to errorBg,
    "debugView.exceptionLabelForeground"        to fg,
    "debugView.stateLabelBackground"            to elementHover,
    "debugView.stateLabelForeground"            to fg,
    "debugView.valueChangedHighlight"           to diffChangeStripe,
    "editor.stackFrameHighlightBackground"      to warningBg,
    "editor.focusedStackFrameHighlightBackground" to successBorder,
    "editor.inlineValuesForeground"             to textMuted,
    "editor.inlineValuesBackground"             to caretRow,

    // Git decorations
    "gitDecoration.addedResourceForeground"          to diffAddStripe,
    "gitDecoration.modifiedResourceForeground"       to diffChangeStripe,
    "gitDecoration.deletedResourceForeground"        to diffDeleteStripe,
    "gitDecoration.renamedResourceForeground"        to constantField,
    "gitDecoration.stageModifiedResourceForeground"  to diffChangeStripe,
    "gitDecoration.stageDeletedResourceForeground"   to diffDeleteStripe,
    "gitDecoration.untrackedResourceForeground"      to functionDecl,
    "gitDecoration.ignoredResourceForeground"        to textPlaceholder,
    "gitDecoration.conflictingResourceForeground"    to diffConflictStripe,
    "gitDecoration.submoduleResourceForeground"      to namedArg,

    // Settings editor
    "settings.headerForeground"        to fg,
    "settings.modifiedItemIndicator"   to keyword,
    "settings.dropdownBackground"      to panelBg,
    "settings.dropdownBorder"          to borderColor,
    "settings.checkboxBackground"      to elementHover,
    "settings.checkboxBorder"          to borderColor,
    "settings.textInputBackground"     to panelBg,
    "settings.textInputBorder"         to borderColor,
    "settings.numberInputBackground"   to panelBg,
    "settings.numberInputBorder"       to borderColor,
    "settings.focusedRowBackground"    to caretRow,
    "settings.focusedRowBorder"        to keyword,
    "settings.rowHoverBackground"      to caretRow,
    "settings.headerBorder"            to borderColor,
    "settings.sashBorder"              to borderColor,

    // Breadcrumbs
    "breadcrumb.background"                to editorBg,
    "breadcrumb.foreground"                to textMuted,
    "breadcrumb.focusForeground"           to fg,
    "breadcrumb.activeSelectionForeground" to fg,
    "breadcrumbPicker.background"          to panelBg,

    // Welcome page, charts
    "welcomePage.background"               to editorBg,
    "welcomePage.tileBackground"           to caretRow,
    "welcomePage.tileHoverBackground"      to elementHover,
    "welcomePage.progress.background"      to elementHover,
    "welcomePage.progress.foreground"      to keyword,
    "walkThrough.embeddedEditorBackground" to caretRow,
    "charts.foreground"                    to fg,
    "charts.lines"                         to borderColor,
    "charts.red"                           to error,
    "charts.blue"                          to diffChangeStripe,
    "charts.yellow"                        to todo,
    "charts.orange"                        to termRed,
    "charts.green"                         to diffAddStripe,
    "charts.purple"                        to functionDecl,

    // Symbol icons (outline, suggest)
    "symbolIcon.arrayForeground"          to fg,
    "symbolIcon.booleanForeground"        to keyword,
    "symbolIcon.classForeground"          to constantField,
    "symbolIcon.colorForeground"          to fg,
    "symbolIcon.constantForeground"       to constantField,
    "symbolIcon.constructorForeground"    to functionDecl,
    "symbolIcon.enumeratorForeground"     to constantField,
    "symbolIcon.enumeratorMemberForeground" to constantField,
    "symbolIcon.eventForeground"          to todo,
    "symbolIcon.fieldForeground"          to fg,
    "symbolIcon.fileForeground"           to fg,
    "symbolIcon.folderForeground"         to fg,
    "symbolIcon.functionForeground"       to functionDecl,
    "symbolIcon.interfaceForeground"      to constantField,
    "symbolIcon.keyForeground"            to keyword,
    "symbolIcon.keywordForeground"        to keyword,
    "symbolIcon.methodForeground"         to functionDecl,
    "symbolIcon.moduleForeground"         to fg,
    "symbolIcon.namespaceForeground"      to fg,
    "symbolIcon.nullForeground"           to keyword,
    "symbolIcon.numberForeground"         to number,
    "symbolIcon.objectForeground"         to fg,
    "symbolIcon.operatorForeground"       to fg,
    "symbolIcon.packageForeground"        to fg,
    "symbolIcon.propertyForeground"       to fg,
    "symbolIcon.referenceForeground"      to fg,
    "symbolIcon.snippetForeground"        to string,
    "symbolIcon.stringForeground"         to string,
    "symbolIcon.structForeground"         to constantField,
    "symbolIcon.textForeground"           to fg,
    "symbolIcon.typeParameterForeground"  to genericTypeParam,
    "symbolIcon.unitForeground"           to number,
    "symbolIcon.variableForeground"       to fg,

    // Testing, problems
    "testing.iconFailed"                       to error,
    "testing.iconErrored"                      to error,
    "testing.iconPassed"                       to diffAddStripe,
    "testing.runAction"                        to diffAddStripe,
    "testing.iconQueued"                       to todo,
    "testing.iconUnset"                        to textPlaceholder,
    "testing.iconSkipped"                      to textMuted,
    "testing.peekBorder"                       to error,
    "testing.peekHeaderBackground"             to errorBg,
    "testing.message.error.badgeBackground"    to error,
    "testing.message.error.badgeForeground"    to editorBg,
    "testing.message.error.lineBackground"     to errorBg,
    "testing.message.info.decorationForeground"  to diffChangeStripe,
    "problemsErrorIcon.foreground"             to error,
    "problemsWarningIcon.foreground"           to todo,
    "problemsInfoIcon.foreground"              to diffChangeStripe,
)

// TextMate scopes. Later rules win, so generic rules come first and the
// exceptions (string/comment punctuation, `new`/`typeof` operators) follow.
private val Palette.tokenColors: List<VsCodeTokenColor> get() = listOf(
    token("Comment", "comment", "punctuation.definition.comment", fg = comment, style = "italic"),
    token("Doc comment", "comment.block.documentation", "comment.block.javadoc", fg = javadoc, style = "italic"),
    token("Doc comment tag", "comment.block.documentation keyword", "comment.block.documentation storage.type.class",
        "comment.block.documentation entity.name.type.instance", fg = javadocTag, style = "italic"),
    token("Doc comment markup", "comment.block.documentation markup", "comment.block.documentation variable", fg = javadocMarkup, style = "italic"),

    token("Keyword", "keyword", "storage", "storage.type", "storage.modifier", "keyword.control", "keyword.other",
        "variable.language.super", fg = keyword),
    token("Operator", "keyword.operator", fg = operator),
    token("Word operator", "keyword.operator.new", "keyword.operator.expression", "keyword.operator.logical.python",
        "keyword.operator.wordlike", fg = keyword),
    token("Language constant", "constant.language", fg = keyword),
    token("Implicit receiver", "variable.language.this", "variable.language.self", "variable.language.it",
        "variable.parameter.function.language.special.self", fg = implicitParam, style = "italic"),

    token("Number", "constant.numeric", "keyword.other.unit", fg = number),
    token("Constant", "variable.other.constant", "constant.other", "variable.other.enummember", fg = constantField, style = "italic"),
    token("Constant character", "constant.character", fg = string),

    token("String", "string", "punctuation.definition.string", fg = string),
    token("String escape", "constant.character.escape", "constant.other.placeholder", "string.regexp",
        "punctuation.definition.template-expression", "punctuation.section.embedded", fg = stringEscape),
    token("Bad string escape", "invalid.illegal.escape", "invalid.illegal.unrecognized-string-escape", fg = stringEscBad),
    token("Embedded code", "meta.embedded", "source.groovy.embedded", fg = fg),

    token("Function declaration", "entity.name.function", "meta.function entity.name.function",
        "meta.definition.method entity.name.function", "meta.method.declaration entity.name.function", fg = functionDecl),
    token("Library function", "support.function", "support.function.builtin", "support.function.console", fg = staticFunc),
    token("Macro / directive", "keyword.control.directive", "meta.preprocessor", "entity.name.function.preprocessor",
        "entity.name.function.macro", fg = staticFunc),
    token("Named argument", "variable.parameter.function.named", "entity.name.function.named-argument",
        "variable.other.readwrite.named-argument", fg = namedArg),

    token("Type", "entity.name.type", "entity.name.class", "entity.name.struct", "entity.name.enum",
        "entity.name.interface", "entity.other.inherited-class", "support.class", "support.type",
        fg = `class`),
    token("Namespace", "entity.name.namespace", "entity.name.module", "entity.name.package", fg = fg),
    token("Variable", "variable", "variable.other", "variable.other.property", "variable.other.object.property",
        "support.variable", "meta.object-literal.key", fg = localVar),
    token("Parameter", "variable.parameter", fg = parameter),

    token("Annotation", "storage.type.annotation", "meta.annotation", "punctuation.definition.annotation",
        "entity.name.function.decorator", "meta.decorator", "meta.decorator punctuation.decorator", fg = annotation),
    token("Annotation attribute", "meta.annotation variable.parameter", "meta.annotation entity.name", fg = annotationNamedAtt),
    token("Label", "entity.name.label", fg = number),

    token("Punctuation", "punctuation", "punctuation.separator", "punctuation.terminator", "punctuation.accessor", fg = punctuation),
    token("Brackets", "punctuation.section", "punctuation.definition.parameters", "punctuation.definition.arguments",
        "punctuation.definition.block", "punctuation.definition.array", "punctuation.definition.dict", "meta.brace",
        "punctuation.definition.begin.bracket", "punctuation.definition.end.bracket", fg = parens),
    token("String punctuation", "punctuation.definition.string", fg = string),
    token("Comment punctuation", "punctuation.definition.comment", fg = comment, style = "italic"),

    token("Tag", "entity.name.tag", "punctuation.definition.tag", "source.css entity.name.tag", fg = keyword),
    token("Attribute", "entity.other.attribute-name", fg = annotationNamedAtt),
    token("CSS class / pseudo", "entity.other.attribute-name.class.css", "entity.other.attribute-name.pseudo-class.css",
        "entity.other.attribute-name.pseudo-element.css", fg = functionDecl),
    token("CSS property", "support.type.property-name.css", "support.type.vendored.property-name.css", fg = fg),
    token("JSON key", "support.type.property-name.json", fg = keyword),
    token("YAML key", "entity.name.tag.yaml", fg = keyword),

    token("Markup heading", "markup.heading", "entity.name.section", "punctuation.definition.heading", fg = functionDecl, style = "bold"),
    token("Markup bold", "markup.bold", style = "bold"),
    token("Markup italic", "markup.italic", style = "italic"),
    token("Markup strikethrough", "markup.strikethrough", style = "strikethrough"),
    token("Markup link URL", "markup.underline.link", "string.other.link.destination", fg = keyword, style = "underline"),
    token("Markup link text", "string.other.link", "string.other.link.title", "markup.link", fg = string, style = "italic"),
    token("Markup quote", "markup.quote", fg = comment, style = "italic"),
    token("Markup code", "markup.inline.raw", "markup.fenced_code.block", "markup.raw.block", fg = string),
    token("Markup list", "punctuation.definition.list", "markup.list punctuation.definition.list_item", fg = keyword),
    token("Markup inserted", "markup.inserted", fg = diffAddStripe),
    token("Markup deleted", "markup.deleted", fg = diffDeleteStripe),
    token("Markup changed", "markup.changed", fg = diffChangeStripe),

    token("Invalid", "invalid", "invalid.illegal", fg = error),
    token("Deprecated", "invalid.deprecated", fg = deprecatedStrikethrough, style = "strikethrough"),
    token("Log: info", "token.info-token", fg = diffChangeStripe),
    token("Log: warning", "token.warn-token", fg = todo),
    token("Log: error", "token.error-token", fg = error),
    token("Log: debug", "token.debug-token", fg = textMuted),
)

// Semantic tokens refine the TextMate colors where the language server knows more:
// declarations vs calls, static/readonly members, mutable variables, deprecations.
private val Palette.semanticTokenColors: Map<String, VsCodeTokenSettings> get() = linkedMapOf(
    "keyword"                  to style(fg = keyword),
    "operator"                 to style(fg = operator),
    "string"                   to style(fg = string),
    "regexp"                   to style(fg = stringEscape),
    "number"                   to style(fg = number),
    "comment"                  to style(fg = comment, style = "italic"),
    "namespace"                to style(fg = fg),
    "class"                    to style(fg = `class`),
    "interface"                to style(fg = `class`),
    "enum"                     to style(fg = `class`),
    "struct"                   to style(fg = `class`),
    "type"                     to style(fg = `class`),
    "typeParameter"            to style(fg = genericTypeParam),
    "enumMember"               to style(fg = constantField, style = "italic"),
    "variable"                 to style(fg = localVar),
    "variable.readonly"        to style(fg = constantField, style = "italic"),
    "variable.readonly.local"  to style(fg = localVar),
    "parameter"                to style(fg = parameter),
    "property"                 to style(fg = fg),
    "property.static.readonly" to style(fg = constantField, style = "italic"),
    "function"                 to style(fg = functionCall),
    "method"                   to style(fg = functionCall),
    "function.declaration"     to style(fg = functionDecl),
    "method.declaration"       to style(fg = functionDecl),
    "function.static"          to style(fg = staticFunc),
    "method.static"            to style(fg = staticFunc),
    "function.defaultLibrary"  to style(fg = staticFunc),
    "macro"                    to style(fg = staticFunc),
    "decorator"                to style(fg = annotation),
    "label"                    to style(fg = number),
    "*.mutable"                to style(style = "underline"),
    "*.deprecated"             to style(style = "strikethrough"),
)

val Palette.vsCodeTheme: VsCodeTheme get() = VsCodeTheme(
    schema = "vscode://schemas/color-theme",
    name = "Darcula Forest",
    type = "dark",
    semanticHighlighting = true,
    colors = workbenchColors.mapValues { hex(it.value) },
    tokenColors = tokenColors,
    semanticTokenColors = semanticTokenColors,
)

@OptIn(ExperimentalSerializationApi::class)
private val vsCodeJson = Json {
    prettyPrint = true
    prettyPrintIndent = "  "
    explicitNulls = false
}

fun Palette.generateVsCodeTheme(): String = vsCodeJson.encodeToString(VsCodeTheme.serializer(), vsCodeTheme)

/** Minimal extension manifest so the folder can be installed or packaged with `vsce`. */
val vsCodePackageJson = """
    {
      "name": "darcula-forest",
      "displayName": "Darcula Forest",
      "description": "A dark green color scheme derived in OKLCH from a handful of constants.",
      "version": "0.1.0",
      "publisher": "oryanm",
      "license": "MIT",
      "engines": { "vscode": "^1.85.0" },
      "categories": ["Themes"],
      "keywords": ["theme", "dark", "green", "oklch", "darcula"],
      "repository": { "type": "git", "url": "https://github.com/oryanm/darcula-forest" },
      "contributes": {
        "themes": [
          {
            "label": "Darcula Forest",
            "uiTheme": "vs-dark",
            "path": "./themes/darcula-forest-color-theme.json"
          }
        ]
      }
    }
""".trimIndent()
