foreground            #acafa9
background            #20231e
cursor                #5f7d31
cursor_text_color     #20231e
selection_foreground  #acafa9
selection_background  #373d32
url_color             #5f7d31

active_border_color   #5f7d31
inactive_border_color #343631

tab_bar_background      #171914
active_tab_foreground   #acafa9
active_tab_background   #20231e
inactive_tab_foreground #9ca099
inactive_tab_background #171914

color0  #20231e
color1  #7e7238
color2  #647b47
color3  #797250
color4  #5f7d31
color5  #8aab5f
color6  #749f2b
color7  #acafa9
color8  #373d32
color9  #7e7238
color10 #647b47
color11 #797250
color12 #5f7d31
color13 #8aab5f
color14 #749f2b
color15 #a3b68d
