-- Darcula Forest
vim.cmd.highlight('clear')
if vim.fn.exists('syntax_on') == 1 then
  vim.cmd.syntax('reset')
end
vim.g.colors_name = 'darcula-forest'
vim.o.background = 'dark'
vim.o.termguicolors = true

local function hl(group, opts)
  vim.api.nvim_set_hl(0, group, opts)
end

-- ── Editor UI ─────────────────────────────────────────────────────
hl('Normal',                   { fg = '#acafa9', bg = '#20231e' })
hl('NormalFloat',              { fg = '#acafa9', bg = '#252722' })
hl('FloatBorder',              { fg = '#343631', bg = '#252722' })
hl('FloatTitle',               { fg = '#8aab5f', bg = '#252722', bold = true })
hl('Cursor',                   { fg = '#20231e', bg = '#acafa9' })
hl('CursorLine',               { bg = '#252722' })
hl('CursorColumn',             { bg = '#252722' })
hl('CursorLineNr',             { fg = '#acafa9', bg = '#252722' })
hl('LineNr',                   { fg = '#545651' })
hl('SignColumn',               { bg = '#2c2f2a' })
hl('FoldColumn',               { fg = '#545651', bg = '#2c2f2a' })
hl('Folded',                   { fg = '#9ca099', bg = '#393c36' })
hl('ColorColumn',              { bg = '#252722' })
hl('WinSeparator',             { fg = '#343631' })
hl('WinBar',                   { fg = '#acafa9', bg = '#20231e' })
hl('WinBarNC',                 { fg = '#85976f', bg = '#20231e' })
hl('StatusLine',               { fg = '#acafa9', bg = '#171914' })
hl('StatusLineNC',             { fg = '#85976f', bg = '#151712' })
hl('TabLine',                  { fg = '#9ca099', bg = '#171914' })
hl('TabLineSel',               { fg = '#acafa9', bg = '#20231e' })
hl('TabLineFill',              { bg = '#151712' })
hl('Visual',                   { bg = '#373d32' })
hl('Search',                   { bg = '#393c36' })
hl('IncSearch',                { fg = '#20231e', bg = '#cbad00' })
hl('CurSearch',                { fg = '#20231e', bg = '#cbad00' })
hl('MatchParen',               { fg = '#b89e00', bg = '#3d3b2f' })
hl('Pmenu',                    { fg = '#acafa9', bg = '#252722' })
hl('PmenuSel',                 { bg = '#393c36' })
hl('PmenuSbar',                { bg = '#252722' })
hl('PmenuThumb',               { bg = '#343631' })
hl('WildMenu',                 { bg = '#393c36' })
hl('QuickFixLine',             { bg = '#373d32' })
hl('NonText',                  { fg = '#70736d' })
hl('SpecialKey',               { fg = '#70736d' })
hl('Whitespace',               { fg = '#70736d' })
hl('EndOfBuffer',              { fg = '#70736d' })
hl('Conceal',                  { fg = '#9ca099' })
hl('Directory',                { fg = '#8aab5f' })
hl('Title',                    { fg = '#8aab5f', bold = true })
hl('ErrorMsg',                 { fg = '#bd4238' })
hl('WarningMsg',               { fg = '#cbad00' })
hl('MoreMsg',                  { fg = '#5f7d31' })
hl('ModeMsg',                  { fg = '#acafa9' })
hl('Question',                 { fg = '#5f7d31' })

-- ── Diff ──────────────────────────────────────────────────────────
hl('DiffAdd',                  { bg = '#343f28' })
hl('DiffDelete',               { fg = '#70736d', bg = '#393c36' })
hl('DiffChange',               { bg = '#2a3c4f' })
hl('DiffText',                 { bg = '#2a3c4f', bold = true })
hl('Added',                    { fg = '#769f36' })
hl('Removed',                  { fg = '#8d908a' })
hl('Changed',                  { fg = '#3d94e0' })

-- ── Spelling ──────────────────────────────────────────────────────
hl('SpellBad',                 { sp = '#584600', undercurl = true })
hl('SpellCap',                 { sp = '#365200', undercurl = true })
hl('SpellLocal',               { sp = '#365200', undercurl = true })
hl('SpellRare',                { sp = '#365200', undercurl = true })

-- ── Classic syntax (fallbacks for non-treesitter buffers) ─────────
hl('Comment',                  { fg = '#808080', italic = true })
hl('Constant',                 { fg = '#749f2b' })
hl('String',                   { fg = '#7e7238' })
hl('Character',                { fg = '#7e7238' })
hl('Number',                   { fg = '#2a8558' })
hl('Boolean',                  { fg = '#5f7d31' })
hl('Float',                    { fg = '#2a8558' })
hl('Identifier',               { fg = '#acafa9' })
hl('Function',                 { fg = '#8aab5f' })
hl('Statement',                { fg = '#5f7d31' })
hl('Operator',                 { fg = '#acafa9' })
hl('PreProc',                  { fg = '#7e7238' })
hl('Type',                     { fg = '#acafa9' })
hl('StorageClass',             { fg = '#5f7d31' })
hl('Structure',                { fg = '#5f7d31' })
hl('Special',                  { fg = '#647b47' })
hl('SpecialChar',              { fg = '#647b47' })
hl('Tag',                      { fg = '#5f7d31' })
hl('Delimiter',                { fg = '#5f7d31' })
hl('SpecialComment',           { fg = '#6d8c40' })
hl('Debug',                    { fg = '#cbad00' })
hl('Underlined',               { underline = true })
hl('Ignore',                   { fg = '#70736d' })
hl('Error',                    { fg = '#bd4238' })
hl('Todo',                     { fg = '#cbad00', bold = true })

-- ── Treesitter captures (mirrors the Helix/Zed mapping) ───────────
hl('@attribute',               { fg = '#85976f' })
hl('@type',                    { fg = '#acafa9' })
hl('@type.builtin',            { fg = '#acafa9' })
hl('@constructor',             { fg = '#8aab5f' })
hl('@constant',                { fg = '#749f2b', italic = true })
hl('@constant.builtin',        { fg = '#5f7d31' })
hl('@number',                  { fg = '#2a8558' })
hl('@string',                  { fg = '#7e7238' })
hl('@string.escape',           { fg = '#647b47' })
hl('@string.regexp',           { fg = '#647b47' })
hl('@string.special',          { fg = '#647b47' })
hl('@comment',                 { fg = '#808080', italic = true })
hl('@comment.documentation',   { fg = '#6d8c40', italic = true })
hl('@comment.todo',            { fg = '#cbad00', bold = true })
hl('@variable',                { fg = '#acafa9' })
hl('@variable.builtin',        { fg = '#83af3e', italic = true })
hl('@variable.parameter',      { fg = '#acafa9' })
hl('@variable.member',         { fg = '#acafa9' })
hl('@label',                   { fg = '#2a8558' })
hl('@punctuation.delimiter',   { fg = '#5f7d31' })
hl('@punctuation.bracket',     { fg = '#acafa9' })
hl('@punctuation.special',     { fg = '#647b47' })
hl('@keyword',                 { fg = '#5f7d31' })
hl('@keyword.directive',       { fg = '#546d32' })
hl('@operator',                { fg = '#acafa9' })
hl('@function',                { fg = '#8aab5f' })
hl('@function.builtin',        { fg = '#546d32' })
hl('@function.macro',          { fg = '#546d32' })
hl('@tag',                     { fg = '#5f7d31' })
hl('@module',                  { fg = '#acafa9' })
hl('@markup.heading',          { fg = '#8aab5f', bold = true })
hl('@markup.list',             { fg = '#5f7d31' })
hl('@markup.bold',             { bold = true })
hl('@markup.italic',           { italic = true })
hl('@markup.strikethrough',    { strikethrough = true })
hl('@markup.link.url',         { fg = '#5f7d31', underline = true })
hl('@markup.link.label',       { fg = '#85976f' })
hl('@markup.quote',            { fg = '#808080', italic = true })
hl('@markup.raw',              { fg = '#7e7238' })
hl('@diff.plus',               { fg = '#769f36' })
hl('@diff.minus',              { fg = '#8d908a' })
hl('@diff.delta',              { fg = '#3d94e0' })

-- ── Diagnostics ───────────────────────────────────────────────────
hl('DiagnosticError',          { fg = '#bd4238' })
hl('DiagnosticWarn',           { fg = '#cbad00' })
hl('DiagnosticInfo',           { fg = '#3d94e0' })
hl('DiagnosticHint',           { fg = '#9ca099' })
hl('DiagnosticUnderlineError', { sp = '#bd4238', undercurl = true })
hl('DiagnosticUnderlineWarn',  { sp = '#cbad00', undercurl = true })
hl('DiagnosticUnderlineInfo',  { sp = '#3d94e0', undercurl = true })
hl('DiagnosticUnderlineHint',  { sp = '#9ca099', undercurl = true })
hl('LspInlayHint',             { fg = '#9ca099', italic = true })
hl('LspReferenceText',         { bg = '#2f312c' })
hl('LspReferenceRead',         { bg = '#2f312c' })
hl('LspReferenceWrite',        { bg = '#2f312c' })
