package darculaforest

fun generateAlacritty() = """
    # Darcula Forest — generated by ./gradlew run
    [colors]
    indexed_colors = [{ index = 16, color = "#${hexOf(editorBg)}" }]

    [colors.primary]
    background = "#${hexOf(editorBg)}"
    foreground = "#${hexOf(fg)}"

    [colors.normal]
    black   = "#${hexOf(editorBg)}"
    red     = "#${hexOf(termRed)}"
    green   = "#${hexOf(stringEscape)}"
    yellow  = "#${hexOf(termYellow)}"
    blue    = "#${hexOf(keyword)}"
    magenta = "#${hexOf(functionDecl)}"
    cyan    = "#${hexOf(constantField)}"
    white   = "#${hexOf(fg)}"

    [colors.bright]
    black   = "#${hexOf(selectionBg)}"
    red     = "#${hexOf(termRed)}"
    green   = "#${hexOf(stringEscape)}"
    yellow  = "#${hexOf(termYellow)}"
    blue    = "#${hexOf(keyword)}"
    magenta = "#${hexOf(functionDecl)}"
    cyan    = "#${hexOf(constantField)}"
    white   = "#${hexOf(termBrightWhite)}"
""".trimIndent()
