package darculaforest

import kotlinx.serialization.ExperimentalSerializationApi
import kotlinx.serialization.json.Json

fun generateCss(): String = buildString {
    appendLine(":root {")
    for (entry in paletteEntries) {
        when (entry) {
            is Section -> {
                appendLine()
                appendLine("    /* ${entry.title} */")
            }
            is Def -> {
                val value = cssOf(entry.variable.value)
                val comment = entry.comment?.let { " /* $it */" } ?: ""
                appendLine("    --${entry.variable.name}: $value;$comment")
            }
            Blank -> appendLine()
        }
    }
    appendLine("}")
}

fun generateIcls(): String = buildString {
    fun opt(name: String, value: String, indent: String) =
        "$indent<option name=\"$name\" value=\"$value\" />"

    fun hex(v: Expr.Var): String = hexOf(v).uppercase()

    appendLine("""<scheme name="Darcula Forest" version="142" parent_scheme="Darcula">""")

    appendLine("  <metaInfo>")
    appendLine("    <property name=\"ide\">idea</property>")
    appendLine("    <property name=\"ideVersion\">2025.3.2.0.0</property>")
    appendLine("    <property name=\"originalScheme\">Darcula Forest</property>")
    appendLine("  </metaInfo>")

    appendLine("  <colors>")
    for (c in iclsColors) {
        appendLine(opt(c.name, hex(c.ref), "    "))
    }
    appendLine("  </colors>")

    appendLine("  <attributes>")
    for (attr in iclsAttributes) {
        if (attr.baseAttributes != null) {
            appendLine("    <option name=\"${attr.name}\" baseAttributes=\"${attr.baseAttributes}\" />")
            continue
        }
        appendLine("    <option name=\"${attr.name}\">")
        appendLine("      <value>")
        attr.fg?.let               { appendLine(opt("FOREGROUND", hex(it), "        ")) }
        attr.bg?.let               { appendLine(opt("BACKGROUND", hex(it), "        ")) }
        attr.fontType?.let         { appendLine(opt("FONT_TYPE", it.value.toString(), "        ")) }
        attr.errorStripeColor?.let { appendLine(opt("ERROR_STRIPE_COLOR", hex(it), "        ")) }
        attr.effectColor?.let      { appendLine(opt("EFFECT_COLOR", hex(it), "        ")) }
        attr.effectType?.let       { appendLine(opt("EFFECT_TYPE", it.value.toString(), "        ")) }
        appendLine("      </value>")
        appendLine("    </option>")
    }
    appendLine("  </attributes>")
    append("</scheme>")
}

fun generateAlacritty(): String = buildString {
    fun hex(v: Expr.Var): String = "\"#${hexOf(v)}\""

    appendLine("# Darcula Forest — generated by ./gradlew run")
    appendLine("[colors]")
    appendLine("indexed_colors = [{ index = 16, color = ${hex(editorBg)} }]")
    appendLine()
    appendLine("[colors.primary]")
    appendLine("background = ${hex(editorBg)}")
    appendLine("foreground = ${hex(fg)}")
    appendLine()
    appendLine("[colors.normal]")
    appendLine("black   = ${hex(editorBg)}")
    appendLine("red     = ${hex(termRed)}")
    appendLine("green   = ${hex(stringEscape)}")
    appendLine("yellow  = ${hex(termYellow)}")
    appendLine("blue    = ${hex(keyword)}")
    appendLine("magenta = ${hex(functionDecl)}")
    appendLine("cyan    = ${hex(constantField)}")
    appendLine("white   = ${hex(fg)}")
    appendLine()
    appendLine("[colors.bright]")
    appendLine("black   = ${hex(selectionBg)}")
    appendLine("red     = ${hex(termRed)}")
    appendLine("green   = ${hex(stringEscape)}")
    appendLine("yellow  = ${hex(termYellow)}")
    appendLine("blue    = ${hex(keyword)}")
    appendLine("magenta = ${hex(functionDecl)}")
    appendLine("cyan    = ${hex(constantField)}")
    append("white   = ${hex(termBrightWhite)}")
}

@OptIn(ExperimentalSerializationApi::class)
private val zedJson = Json {
    prettyPrint = true
    prettyPrintIndent = "  "
}

fun generateZed(): String = zedJson.encodeToString(ZedTheme.serializer(), zedTheme)
