package darculaforest

import kotlinx.serialization.ExperimentalSerializationApi
import kotlinx.serialization.json.Json

fun generateCss(): String = buildString {
    appendLine(":root {")
    for (entry in paletteEntries) {
        when (entry) {
            is Section -> {
                appendLine()
                appendLine("    /* ${entry.title} */")
            }
            is Def -> {
                val value = cssOf(entry.variable.value)
                val comment = entry.comment?.let { " /* $it */" } ?: ""
                appendLine("    --${entry.variable.name}: $value;$comment")
            }
            Blank -> appendLine()
        }
    }
    appendLine("}")
}

fun generateIcls(): String = buildString {
    fun opt(name: String, value: String, indent: String) =
        "$indent<option name=\"$name\" value=\"$value\" />"

    fun hex(v: Expr.Var): String = hexOf(v).uppercase()

    appendLine("""<scheme name="Darcula Forest" version="142" parent_scheme="Darcula">""")

    appendLine("  <metaInfo>")
    appendLine("    <property name=\"ide\">idea</property>")
    appendLine("    <property name=\"ideVersion\">2025.3.2.0.0</property>")
    appendLine("    <property name=\"originalScheme\">Darcula Forest</property>")
    appendLine("  </metaInfo>")

    appendLine("  <colors>")
    for (c in iclsColors) {
        appendLine(opt(c.name, hex(c.ref), "    "))
    }
    appendLine("  </colors>")

    appendLine("  <attributes>")
    for (attr in iclsAttributes) {
        if (attr.baseAttributes != null) {
            appendLine("    <option name=\"${attr.name}\" baseAttributes=\"${attr.baseAttributes}\" />")
            continue
        }
        appendLine("    <option name=\"${attr.name}\">")
        appendLine("      <value>")
        attr.fg?.let               { appendLine(opt("FOREGROUND", hex(it), "        ")) }
        attr.bg?.let               { appendLine(opt("BACKGROUND", hex(it), "        ")) }
        attr.fontType?.let         { appendLine(opt("FONT_TYPE", it.value.toString(), "        ")) }
        attr.errorStripeColor?.let { appendLine(opt("ERROR_STRIPE_COLOR", hex(it), "        ")) }
        attr.effectColor?.let      { appendLine(opt("EFFECT_COLOR", hex(it), "        ")) }
        attr.effectType?.let       { appendLine(opt("EFFECT_TYPE", it.value.toString(), "        ")) }
        appendLine("      </value>")
        appendLine("    </option>")
    }
    appendLine("  </attributes>")
    append("</scheme>")
}

fun generateAlacritty() = """
    # Darcula Forest — generated by ./gradlew run
    [colors]
    indexed_colors = [{ index = 16, color = "#${hexOf(editorBg)}" }]

    [colors.primary]
    background = "#${hexOf(editorBg)}"
    foreground = "#${hexOf(fg)}"

    [colors.normal]
    black   = "#${hexOf(editorBg)}"
    red     = "#${hexOf(termRed)}"
    green   = "#${hexOf(stringEscape)}"
    yellow  = "#${hexOf(termYellow)}"
    blue    = "#${hexOf(keyword)}"
    magenta = "#${hexOf(functionDecl)}"
    cyan    = "#${hexOf(constantField)}"
    white   = "#${hexOf(fg)}"

    [colors.bright]
    black   = "#${hexOf(selectionBg)}"
    red     = "#${hexOf(termRed)}"
    green   = "#${hexOf(stringEscape)}"
    yellow  = "#${hexOf(termYellow)}"
    blue    = "#${hexOf(keyword)}"
    magenta = "#${hexOf(functionDecl)}"
    cyan    = "#${hexOf(constantField)}"
    white   = "#${hexOf(termBrightWhite)}"
""".trimIndent()

@OptIn(ExperimentalSerializationApi::class)
private val zedJson = Json {
    prettyPrint = true
    prettyPrintIndent = "  "
}

fun generateZed(): String = zedJson.encodeToString(ZedTheme.serializer(), zedTheme)
